# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"

df = pd.read_csv(url, index_col=0)

In [3]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [4]:
df.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,48029,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,0,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,22139,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [5]:
df.shape

(10910, 25)

In [6]:
df.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employmentstatus', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type'],
      dtype='str')

In [7]:
low_claim_yes = df.loc[
    (df["total_claim_amount"] < 1000)
    & (df["response"] == "Yes")
].copy()

In [8]:
low_claim_yes

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [9]:
low_claim_yes.shape[0]

1399

In [10]:
responded_yes = df.loc[df["response"] == "Yes"].copy()

In [11]:
policy_analysis = responded_yes.groupby(["policy_type", "gender"]
).agg(
    average_monthly_premium=("monthly_premium_auto", "mean"),
    average_customer_lifetime_value=("customer_lifetime_value", "mean"),
    average_total_claim=("total_claim_amount", "mean"),
    number_of_customers=("customer", "count")
).round(2)

In [12]:
policy_analysis

                       average_monthly_premium  \
policy_type    gender
Corporate Auto F                         94.30
               M                         92.19
Personal Auto  F                         99.00
               M                         91.09
Special Auto   F                         92.31
               M                         86.34

                       average_customer_lifetime_value  average_total_claim  \
policy_type    gender
Corporate Auto F                               7712.63               433.74
               M                               7944.47               408.58
Personal Auto  F                               8339.79               452.97
               M                               7448.38               457.01
Special Auto   F                               7691.58               453.28
               M                               8247.09               429.53

                       number_of_customers
policy_type    gender
Corporate Auto F                       169
               M                       154
Personal Auto  F                       540
               M                       536
Special Auto   F                        35
               M                        32

In [13]:
policy_analysis.sort_values(
    by="average_customer_lifetime_value",
    ascending=False
)

                       average_monthly_premium  \
policy_type    gender
Personal Auto  F                         99.00
Special Auto   M                         86.34
Corporate Auto M                         92.19
               F                         94.30
Special Auto   F                         92.31
Personal Auto  M                         91.09

                       average_customer_lifetime_value  average_total_claim  \
policy_type    gender
Personal Auto  F                               8339.79               452.97
Special Auto   M                               8247.09               429.53
Corporate Auto M                               7944.47               408.58
               F                               7712.63               433.74
Special Auto   F                               7691.58               453.28
Personal Auto  M                               7448.38               457.01

                       number_of_customers
policy_type    gender
Personal Auto  F                       540
Special Auto   M                        32
Corporate Auto M                       154
               F                       169
Special Auto   F                        35
Personal Auto  M                       536

In [14]:
policy_analysis.sort_values(
    by="average_total_claim",
    ascending=True
)

,,average_monthly_premium,average_customer_lifetime_value,average_total_claim,number_of_customers
policy_type,gender,,,,
Corporate Auto,M,92.19,7944.47,408.58,154
Special Auto,M,86.34,8247.09,429.53,32
Corporate Auto,F,94.30,7712.63,433.74,169
Personal Auto,F,99.00,8339.79,452.97,540
Special Auto,F,92.31,7691.58,453.28,35
Personal Auto,M,91.09,7448.38,457.01,536

In [15]:
customers_by_state = (
    df.groupby("state")["customer"]
    .count()
    .sort_values(ascending=False)
)

In [16]:
customers_by_state

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: customer, dtype: int64

In [17]:
states_over_500 = customers_by_state[
    customers_by_state > 500
]

In [18]:
states_over_500

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: customer, dtype: int64

In [21]:
clv_by_education_gender = df.groupby(
    ["education", "gender"]
)["customer_lifetime_value"].agg(
    ["max", "min", "median"]
).round(2)

In [22]:
clv_by_education_gender

                                  max      min   median
education            gender
Bachelor             F       73225.96  1904.00  5640.51
                     M       67907.27  1898.01  5548.03
College              F       61850.19  1898.68  5623.61
                     M       61134.68  1918.12  6005.85
Doctor               F       44856.11  2395.57  5332.46
                     M       32677.34  2267.60  5577.67
High School or Below F       55277.45  2144.92  6039.55
                     M       83325.38  1940.98  6286.73
Master               F       51016.07  2417.78  5729.86
                     M       50568.26  2272.31  5579.10

In [24]:
clv_by_education_gender.sort_values(
    by="median",
    ascending=False
)

                                  max      min   median
education            gender
High School or Below M       83325.38  1940.98  6286.73
                     F       55277.45  2144.92  6039.55
College              M       61134.68  1918.12  6005.85
Master               F       51016.07  2417.78  5729.86
Bachelor             F       73225.96  1904.00  5640.51
College              F       61850.19  1898.68  5623.61
Master               M       50568.26  2272.31  5579.10
Doctor               M       32677.34  2267.60  5577.67
Bachelor             M       67907.27  1898.01  5548.03
Doctor               F       44856.11  2395.57  5332.46

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here